version: "3"
services:
  message:
    build: message/
    ports:
      - "9007:9007"
    links:
      - messageapp
      - mongodb_message
      - replica_message
      - redis
      - credit
    depends_on:
      - messageapp
      - mongodb_message
      - replica_message
      - redis
  credit:
    build: credit/
    ports:
      - "9017:9017"
    links:
      - mongodb_credit
      - replica_credit
      - redis
    depends_on:
      - mongodb_credit
      - replica_credit
      - redis
  messageapp:
    image: cabify/backend-bootcamp-messageapp
    ports:
      - "3000:3000"

  mongodbcredit:
    image: mongo
    command: mongod --port 27017    
    volumes:
      - ./credit/data/db:/credit/data/db
    ports:
      - 27017:27017
  replicacredit:
    image: mongo
    command: mongod --port 27018    
    volumes:
      - ./credit/data/replica:/credit/data/replica
    ports:
      - 27018:27018

  mongodbmessage:
    image: mongo
    command: mongod --port 27027
    volumes:
      - ./message/data/db:/message/data/db
    ports:
      - 27027:27027
  replicamessage:
    image: mongo
    command: mongod --port 27028
    volumes:
      - ./message/data/replica:/message/data/replica
    ports:
      - 27028:27028

  redis:
    image: redis
    ports:
      - 6379:6379